#!/usr/bin/env node
/**
 * Compile prompts/*.txt → includes/grayfox-prompts.php
 *
 * Each .txt file becomes one PHP constant:
 *   chat-system.txt     → GRAYFOX_PROMPT_CHAT_SYSTEM
 *   classifier.txt      → GRAYFOX_PROMPT_CLASSIFIER
 *   rag-summarize.txt   → GRAYFOX_PROMPT_RAG_SUMMARIZE
 *   rag-retrieve.txt    → GRAYFOX_PROMPT_RAG_RETRIEVE
 *   chat-kb-tool.txt    → GRAYFOX_PROMPT_CHAT_KB_TOOL
 *   chat-kb-prefetch.txt → GRAYFOX_PROMPT_CHAT_KB_PREFETCH
 *
 * Template variables in prompt files (substituted at PHP runtime, not here):
 *   {{KB_SECTION}}      — chat-system.txt: replaced with tool or prefetch KB block
 *   {{KNOWLEDGE_JSON}}  — chat-kb-prefetch.txt: replaced with KB JSON content
 *   {{KB_CONTEXT}}      — classifier.txt: replaced with truncated KB summary
 *   {{HISTORY_CONTEXT}} — classifier.txt: replaced with last 3 conversation messages
 *
 * Usage:
 *   node scripts/build-prompts.js
 *   npm run build:prompts
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT        = path.join(__dirname, '..');
const PROMPTS_DIR = path.join(ROOT, 'prompts');
const OUTPUT_FILE = path.join(ROOT, 'includes', 'grayfox-prompts.php');
const NOWDOC_ID   = 'GRAYFOX_NOWDOC';

/**
 * Convert a filename to a PHP constant name.
 * e.g. "chat-system.txt" → "GRAYFOX_PROMPT_CHAT_SYSTEM"
 */
function toConstantName(filename) {
	return 'GRAYFOX_PROMPT_' + filename
		.replace(/\.txt$/, '')
		.toUpperCase()
		.replace(/-/g, '_');
}

// Collect and sort .txt files for deterministic output.
const files = fs.readdirSync(PROMPTS_DIR)
	.filter(f => f.endsWith('.txt'))
	.sort();

if (files.length === 0) {
	console.error('ERROR: No .txt files found in prompts/');
	process.exit(1);
}

// Validate: the nowdoc terminator must not appear inside any prompt file.
for (const file of files) {
	const content = fs.readFileSync(path.join(PROMPTS_DIR, file), 'utf8');
	if (content.split('\n').some(line => line.trimEnd() === NOWDOC_ID)) {
		console.error(`ERROR: Nowdoc terminator "${NOWDOC_ID}" found inside ${file}. Rename the terminator.`);
		process.exit(1);
	}
}

const timestamp = new Date().toISOString();

let php = `<?php
/**
 * Compiled prompt constants.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Edit source files in prompts/ then regenerate:
 *   npm run build:prompts
 *
 * Generated: ${timestamp}
 *
 * @package GrayFox
 */

if ( ! defined( 'ABSPATH' ) ) {
\texit;
}

`;

for (const file of files) {
	const content  = fs.readFileSync(path.join(PROMPTS_DIR, file), 'utf8');
	const constant = toConstantName(file);
	// PHP nowdoc — content is never interpolated, safe for any string.
	php += `define( '${constant}', <<<'${NOWDOC_ID}'\n${content}\n${NOWDOC_ID}\n);\n\n`;
}

fs.writeFileSync(OUTPUT_FILE, php, 'utf8');
console.log(`Built ${files.length} prompt(s) → includes/grayfox-prompts.php`);
files.forEach(f => console.log(`  ${f} → ${toConstantName(f)}`));
