<?php
/**
 * Generate functions.php — WordPress theme setup, asset loading, pattern registration.
 *
 * Ported from wp-theme-builder/src/functions_php_builder.py
 *
 * @package GrayFox
 */

// phpcs:disable WordPress.Security.EscapeOutput.OutputNotEscaped
// -- This file is a PHP code generator (ob_start/ob_get_clean). Its output is
// -- written to on-disk theme files, not echoed to the browser. Variables are
// -- pre-sanitized (esc_html/esc_attr/intval) at the point of user input.

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class GrayFox_TB_FunctionsPHPBuilder
 */
class GrayFox_TB_FunctionsPHPBuilder {

	private const BOOTSTRAP_VERSION       = '5.3.3';
	private const BOOTSTRAP_ICONS_VERSION = '1.11.3';

	/**
	 * Generate the complete functions.php content for a theme.
	 *
	 * @param array $theme  manifest['theme'] block.
	 * @param array $assets manifest['assets'] block.
	 * @return string Complete functions.php string.
	 */
	public static function build( array $theme, array $assets = [] ): string {
		$name = $theme['name'] ?? 'Custom Theme';
		$slug = $theme['slug'] ?? 'custom-theme';
		$typo = $theme['typography'] ?? [];

		$heading_font = $typo['heading_font'] ?? 'Inter';
		$body_font    = $typo['body_font']    ?? 'Inter';

		$fonts_url = GrayFox_TB_ColorUtils::build_google_fonts_url( $heading_font, $body_font );
		$generated = gmdate( 'Y-m-d H:i:s' );
		$version   = gmdate( 'Y.m.d' );

		// Escape for PHP string embedding.
		$php_name = str_replace( "'", "\\'", $name );
		$php_slug = str_replace( "'", "\\'", $slug );

		// PHP function-name-safe slug.
		$fn_prefix = str_replace( '-', '_', $slug );

		// Build @font-face for locally hosted fonts.
		$local_font_css_parts = [];
		foreach ( [ $heading_font, $body_font ] as $font ) {
			if ( GrayFox_TB_ColorUtils::is_local_font( $font ) ) {
				$bare                   = GrayFox_TB_ColorUtils::strip_local_prefix( $font );
				$local_font_css_parts[] = GrayFox_TB_ColorUtils::build_font_face_css( $bare );
			}
		}
		$local_font_css = implode( "\n", $local_font_css_parts );

		// Build fonts enqueue snippet.
		$fonts_enqueue_block = '';
		if ( $fonts_url ) {
			ob_start(); ?>
	wp_enqueue_style(
		'<?php echo $php_slug; ?>-fonts',
		'<?php echo $fonts_url; ?>',
		array(),
		null
	);
			<?php $fonts_enqueue_block .= ob_get_clean();
			$fonts_enqueue_block .= "\n";
		}

		if ( $local_font_css ) {
			$escaped_css          = str_replace( [ '\\', "'" ], [ '\\\\', "\\'" ], $local_font_css );
			ob_start(); ?>
	wp_add_inline_style(
		'<?php echo $php_slug; ?>-style',
		'<?php echo $escaped_css; ?>'
	);
			<?php $fonts_enqueue_block .= ob_get_clean();
			$fonts_enqueue_block .= "\n";
		}

		// Conditional asset enqueues based on manifest.assets flags.
		$load_forms   = ! empty( $assets['load_gf_forms'] );
		$load_icons   = ! empty( $assets['load_bootstrap_icons'] );
		$load_js      = true;

		$bs_ver = self::BOOTSTRAP_VERSION;
		$bi_ver = self::BOOTSTRAP_ICONS_VERSION;

		// Bootstrap CSS is always required — all patterns depend on Bootstrap utilities.
		// Files are copied locally into the theme's assets/ dir by copy_bootstrap_assets().
		ob_start(); ?>
	wp_enqueue_style(
		'<?php echo $php_slug; ?>-bootstrap',
		get_stylesheet_directory_uri() . '/assets/css/bootstrap.min.css',
		array(),
		'<?php echo $bs_ver; ?>'
	);
		<?php $bootstrap_css_enqueue  = ob_get_clean();
		$bootstrap_css_enqueue .= "\n";

		$forms_enqueue = $load_forms ? self::enqueue_style_line( $php_slug, 'forms', '/assets/css/gf-forms.css', $version ) : '';

		if ( $load_icons ) {
			ob_start(); ?>
	wp_enqueue_style(
		'<?php echo $php_slug; ?>-icons',
		get_stylesheet_directory_uri() . '/assets/css/bootstrap-icons.min.css',
		array(),
		'<?php echo $bi_ver; ?>'
	);
			<?php $icons_enqueue  = ob_get_clean();
			$icons_enqueue .= "\n";
		} else {
			$icons_enqueue = '';
		}

		if ( $load_js ) {
			ob_start(); ?>
	wp_enqueue_script(
		'<?php echo $php_slug; ?>-bootstrap',
		get_stylesheet_directory_uri() . '/assets/js/bootstrap.bundle.min.js',
		array(),
		'<?php echo $bs_ver; ?>',
		true
	);
			<?php $js_enqueue  = ob_get_clean();
			$js_enqueue .= "\n";
		} else {
			$js_enqueue = '';
		}

		// gf-theme.js is always enqueued — all interactive GF components depend on it.
		ob_start(); ?>
	wp_enqueue_script(
		'<?php echo $php_slug; ?>-theme-js',
		get_stylesheet_directory_uri() . '/assets/js/gf-theme.js',
		array(),
		'<?php echo $version; ?>',
		true
	);
		<?php $gf_js_enqueue  = ob_get_clean();
		$gf_js_enqueue .= "\n";

		// Open PHP tag — needs to be a literal string here (cannot be inside ob_start block).
		$open_php = '<?php';

		ob_start(); ?>
<?php echo $open_php; ?>

/**
 * <?php echo $php_name; ?> -- Theme Functions
 * Generated by GrayFox Theme Builder on <?php echo $generated; ?>
 *
 * @package <?php echo $php_slug; ?>
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Theme setup.
 */
function <?php echo $fn_prefix; ?>_setup(): void {
	add_theme_support( 'wp-block-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'core-block-patterns' );
}
add_action( 'after_setup_theme', '<?php echo $fn_prefix; ?>_setup' );

/**
 * Enqueue fonts and theme assets.
 */
function <?php echo $fn_prefix; ?>_enqueue_assets(): void {
<?php echo $fonts_enqueue_block; ?>	wp_enqueue_style(
		'<?php echo $php_slug; ?>-style',
		get_stylesheet_uri(),
		array(),
		'<?php echo $version; ?>'
	);
<?php echo $bootstrap_css_enqueue; ?><?php echo $forms_enqueue; ?><?php echo $icons_enqueue; ?><?php echo $js_enqueue; ?><?php echo $gf_js_enqueue; ?>}
add_action( 'wp_enqueue_scripts',   '<?php echo $fn_prefix; ?>_enqueue_assets' );
add_action( 'enqueue_block_assets', '<?php echo $fn_prefix; ?>_enqueue_assets' );

/**
 * Register custom block pattern category.
 */
function <?php echo $fn_prefix; ?>_register_patterns(): void {
	register_block_pattern_category(
		'<?php echo $php_slug; ?>-sections',
		array( 'label' => __( '<?php echo $php_name; ?> Sections', '<?php echo $php_slug; ?>' ) )
	);
}
add_action( 'init', '<?php echo $fn_prefix; ?>_register_patterns' );

/**
 * Seed a Footer Menu navigation post on theme activation.
 */
function <?php echo $fn_prefix; ?>_seed_footer_nav(): void {
	if ( get_page_by_path( 'footer', OBJECT, 'wp_navigation' ) ) {
		return;
	}
	wp_insert_post( array(
		'post_type'    => 'wp_navigation',
		'post_title'   => 'Footer Menu',
		'post_name'    => 'footer',
		'post_status'  => 'publish',
		'post_content' =>
			'<!-- wp:navigation-link {"label":"Home","url":"/"} /-->' .
			'<!-- wp:navigation-link {"label":"About","url":"/about"} /-->' .
			'<!-- wp:navigation-link {"label":"Services","url":"/services"} /-->' .
			'<!-- wp:navigation-link {"label":"Contact","url":"/contact"} /-->',
	) );
}
add_action( 'after_switch_theme', '<?php echo $fn_prefix; ?>_seed_footer_nav' );
		<?php return ob_get_clean();
	}

	// -------------------------------------------------------------------------
	// Private helpers
	// -------------------------------------------------------------------------

	/**
	 * Build a wp_enqueue_style() call line.
	 */
	private static function enqueue_style_line( string $slug, string $handle, string $path, string $version ): string {
		ob_start(); ?>
	wp_enqueue_style(
		'<?php echo $slug; ?>-<?php echo $handle; ?>',
		get_template_directory_uri() . '<?php echo $path; ?>',
		array(),
		'<?php echo $version; ?>'
	);
		<?php
		return ob_get_clean() . "\n";
	}

	/**
	 * Download Bootstrap CSS/JS into the generated theme's assets/ directory.
	 *
	 * Called by GrayFox_ThemeBuilder after all theme files are written.
	 * Fetches from CDN once at theme-generation time so the theme itself
	 * serves Bootstrap locally — satisfying WP Guideline 8.
	 *
	 * @param string $theme_dir    Absolute path to the generated theme directory.
	 * @param bool   $include_icons Whether to also download Bootstrap Icons CSS.
	 * @return bool True on success, false if any download failed.
	 */
	public static function copy_bootstrap_assets( string $theme_dir, bool $include_icons = false ): bool {
		$bs_ver  = self::BOOTSTRAP_VERSION;
		$bi_ver  = self::BOOTSTRAP_ICONS_VERSION;
		$css_dir = $theme_dir . '/assets/css';
		$js_dir  = $theme_dir . '/assets/js';

		wp_mkdir_p( $css_dir );

		$downloads = array(
			$css_dir . '/bootstrap.min.css'        => 'https://cdn.jsdelivr.net/npm/bootstrap@' . $bs_ver . '/dist/css/bootstrap.min.css',
			$js_dir  . '/bootstrap.bundle.min.js'  => 'https://cdn.jsdelivr.net/npm/bootstrap@' . $bs_ver . '/dist/js/bootstrap.bundle.min.js',
		);

		if ( $include_icons ) {
			$downloads[ $css_dir . '/bootstrap-icons.min.css' ] = 'https://cdn.jsdelivr.net/npm/bootstrap-icons@' . $bi_ver . '/font/bootstrap-icons.min.css';
		}

		foreach ( $downloads as $dest => $url ) {
			$response = wp_remote_get( $url, array( 'timeout' => 20 ) );
			if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
				if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
					error_log( 'GrayFox Theme Builder: failed to download Bootstrap asset: ' . $url ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
				}
				return false;
			}
			global $wp_filesystem;
			if ( $wp_filesystem ) {
				$wp_filesystem->put_contents( $dest, wp_remote_retrieve_body( $response ), FS_CHMOD_FILE );
			} else {
				// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
				file_put_contents( $dest, wp_remote_retrieve_body( $response ) );
			}
		}

		return true;
	}

	/**
	 * Build a wp_enqueue_script() call line (footer).
	 */
	private static function enqueue_script_line( string $slug, string $handle, string $path, string $version ): string {
		ob_start(); ?>
	wp_enqueue_script(
		'<?php echo $slug; ?>-<?php echo $handle; ?>',
		get_template_directory_uri() . '<?php echo $path; ?>',
		array(),
		'<?php echo $version; ?>',
		true
	);
		<?php
		return ob_get_clean() . "\n";
	}
}
