<?php
/**
 * Generates assets/js/gf-theme.js for the built theme.
 *
 * Centralises all GrayFox custom interactive component logic so patterns
 * never need inline <script> tags. Bootstrap data-bs-* components
 * (accordion, tabs, collapse) are auto-initialised by bootstrap.bundle.min.js
 * and need no code here — only GF-specific components live in this file.
 *
 * @package GrayFox
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class GrayFox_TB_JSBuilder
 */
class GrayFox_TB_JSBuilder {

	/**
	 * Returns the contents of gf-theme.js for the generated theme.
	 */
	public static function build(): string {
		ob_start(); ?>
/**
 * GrayFox Theme — Interactive Components
 * Generated by GrayFox Theme Builder
 *
 * Bootstrap data-bs-* components (accordion, tabs, collapse, modal) are
 * auto-initialised by bootstrap.bundle.min.js — no code needed here for those.
 * This file handles GF-specific custom components only.
 */
(function () {
  'use strict';

  // ── Chatbot Widget ──────────────────────────────────────────────────────────
  // Launcher toggles the panel; icons swap; close button collapses.
  document.querySelectorAll('.gf-chatbot__launcher').forEach(function (launcher) {
    var panelId  = launcher.getAttribute('aria-controls');
    var panel    = panelId ? document.getElementById(panelId) : null;
    if (!panel) return;
    var closeBtn = panel.querySelector('.gf-chatbot__close');
    var badge    = launcher.querySelector('.gf-chatbot__badge');

    function open() {
      panel.hidden = false;
      launcher.setAttribute('aria-expanded', 'true');
      if (badge) badge.hidden = true;
    }
    function close() {
      panel.hidden = true;
      launcher.setAttribute('aria-expanded', 'false');
    }

    launcher.addEventListener('click', function () {
      panel.hidden ? open() : close();
    });
    if (closeBtn) closeBtn.addEventListener('click', close);
  });

  // ── Screenshot Carousel ─────────────────────────────────────────────────────
  // Drives gf-carousel-wrapper: tab buttons, dot buttons, prev/next arrows.
  // Each wrapper is independent so multiple carousels on one page work correctly.
  function gfCarouselGoTo(wrapper, idx) {
    wrapper.querySelectorAll('.gf-carousel-slide').forEach(function (s, i) {
      s.classList.toggle('gf-carousel-slide--active', i === idx);
    });
    wrapper.querySelectorAll('.gf-carousel-tab').forEach(function (t, i) {
      t.classList.toggle('gf-carousel-tab--active', i === idx);
    });
    wrapper.querySelectorAll('.gf-carousel-dot').forEach(function (d, i) {
      d.classList.toggle('gf-carousel-dot--active', i === idx);
    });
  }

  window.gfCarouselPrev = function (btn) {
    var w      = btn.closest('.gf-carousel-wrapper');
    var slides = w.querySelectorAll('.gf-carousel-slide');
    var cur    = Array.from(slides).findIndex(function (s) {
      return s.classList.contains('gf-carousel-slide--active');
    });
    gfCarouselGoTo(w, (cur - 1 + slides.length) % slides.length);
  };

  window.gfCarouselNext = function (btn) {
    var w      = btn.closest('.gf-carousel-wrapper');
    var slides = w.querySelectorAll('.gf-carousel-slide');
    var cur    = Array.from(slides).findIndex(function (s) {
      return s.classList.contains('gf-carousel-slide--active');
    });
    gfCarouselGoTo(w, (cur + 1) % slides.length);
  };

  document.querySelectorAll('.gf-carousel-tab, .gf-carousel-dot').forEach(function (el) {
    el.addEventListener('click', function () {
      gfCarouselGoTo(
        el.closest('.gf-carousel-wrapper'),
        parseInt(el.dataset.slide, 10)
      );
    });
  });

  // ── Lightbox ────────────────────────────────────────────────────────────────
  // Opens a full-screen overlay showing the clicked image; arrow/keyboard nav.
  var gfLightboxCurrent = 1;

  window.gfLightboxOpen = function (btn, idx) {
    gfLightboxCurrent = idx;
    var grid  = btn.closest ? btn.closest('.gf-lightbox-grid-wrap')
                             : document.querySelector('.gf-lightbox-grid-wrap');
    var thumb = grid ? grid.querySelectorAll('.gf-lightbox-thumb-img')[idx - 1] : null;
    var modal = document.getElementById('gf-lightbox-modal');
    var img   = document.getElementById('gf-lightbox-img');
    if (!modal || !img) return;
    img.src            = thumb ? thumb.src : '';
    img.alt            = thumb ? (thumb.alt || '') : '';
    modal.style.display = 'flex';
    document.body.style.overflow = 'hidden';
  };

  window.gfLightboxClose = function () {
    var modal = document.getElementById('gf-lightbox-modal');
    if (modal) modal.style.display = 'none';
    document.body.style.overflow = '';
  };

  window.gfLightboxPrev = function () {
    var grid  = document.querySelector('.gf-lightbox-grid-wrap');
    var total = grid ? grid.querySelectorAll('.gf-lightbox-thumb-img').length : 0;
    if (gfLightboxCurrent > 1) {
      gfLightboxOpen({ closest: function () { return grid; } }, gfLightboxCurrent - 1);
    }
  };

  window.gfLightboxNext = function () {
    var grid  = document.querySelector('.gf-lightbox-grid-wrap');
    var total = grid ? grid.querySelectorAll('.gf-lightbox-thumb-img').length : 0;
    if (gfLightboxCurrent < total) {
      gfLightboxOpen({ closest: function () { return grid; } }, gfLightboxCurrent + 1);
    }
  };

  document.addEventListener('keydown', function (e) {
    var modal = document.getElementById('gf-lightbox-modal');
    if (!modal || modal.style.display === 'none') return;
    if (e.key === 'Escape')      gfLightboxClose();
    if (e.key === 'ArrowLeft')   gfLightboxPrev();
    if (e.key === 'ArrowRight')  gfLightboxNext();
  });

  // ── Modal / Overlay Dismiss ─────────────────────────────────────────────────
  // Plays the gf-is-hiding exit animation then sets hidden on the element.
  function gfDismiss(el) {
    if (!el || el.hidden) return;
    el.classList.add('gf-is-hiding');
    el.addEventListener('animationend', function () {
      el.hidden = true;
      el.classList.remove('gf-is-hiding');
    }, { once: true });
  }

  // Cookie consent bar — accept or decline hides the bar.
  document.querySelectorAll('.gf-cookie-accept, .gf-cookie-decline').forEach(function (btn) {
    btn.addEventListener('click', function () { gfDismiss(btn.closest('.gf-cookie-bar')); });
  });

  // Cookie consent modal — save or accept all hides the modal.
  document.querySelectorAll('.gf-cookie-save, .gf-cookie-accept-all').forEach(function (btn) {
    btn.addEventListener('click', function () { gfDismiss(btn.closest('.gf-cookie-modal')); });
  });

  // Opt-in popup — close button, dismiss link, or backdrop click.
  document.querySelectorAll('.gf-opt-in-popup__close, .gf-opt-in-popup__dismiss').forEach(function (btn) {
    btn.addEventListener('click', function () { gfDismiss(btn.closest('.gf-opt-in-popup')); });
  });
  document.querySelectorAll('.gf-opt-in-popup__backdrop').forEach(function (bd) {
    bd.addEventListener('click', function () { gfDismiss(bd.closest('.gf-opt-in-popup')); });
  });

  // Announcement modal — close button, dismiss link, or backdrop click.
  document.querySelectorAll('.gf-announcement-modal__close, .gf-announcement-modal__dismiss').forEach(function (btn) {
    btn.addEventListener('click', function () { gfDismiss(btn.closest('.gf-announcement-modal')); });
  });
  document.querySelectorAll('.gf-announcement-modal__backdrop').forEach(function (bd) {
    bd.addEventListener('click', function () { gfDismiss(bd.closest('.gf-announcement-modal')); });
  });

  // Age gate — yes hides the gate; no navigates back.
  document.querySelectorAll('.gf-age-gate__yes').forEach(function (btn) {
    btn.addEventListener('click', function () { gfDismiss(btn.closest('.gf-age-gate')); });
  });
  document.querySelectorAll('.gf-age-gate__no').forEach(function (btn) {
    btn.addEventListener('click', function () { history.back(); });
  });

  // Push notification banner — allow or dismiss hides the banner.
  document.querySelectorAll('.gf-push-banner__allow, .gf-push-banner__dismiss').forEach(function (btn) {
    btn.addEventListener('click', function () { gfDismiss(btn.closest('.gf-push-banner__inner')); });
  });

  // Escape key closes any visible GF overlay.
  document.addEventListener('keydown', function (e) {
    if (e.key !== 'Escape') return;
    ['.gf-cookie-modal', '.gf-opt-in-popup', '.gf-announcement-modal'].forEach(function (sel) {
      document.querySelectorAll(sel).forEach(function (el) { if (!el.hidden) gfDismiss(el); });
    });
  });

  // ── Floating Contact Group ──────────────────────────────────────────────────
  // Toggle button shows/hides the action cluster; chatbot-trigger opens the bot.
  document.querySelectorAll('.gf-floating-contacts__toggle').forEach(function (toggle) {
    var contacts = toggle.closest('.gf-floating-contacts');
    var actions  = contacts ? contacts.querySelector('.gf-floating-contacts__actions') : null;
    if (!actions) return;
    toggle.addEventListener('click', function () {
      var isOpen = toggle.getAttribute('aria-expanded') === 'true';
      toggle.setAttribute('aria-expanded', isOpen ? 'false' : 'true');
      actions.classList.toggle('is-open', !isOpen);
    });
  });

  document.querySelectorAll('.gf-chatbot-trigger').forEach(function (btn) {
    btn.addEventListener('click', function () {
      var launcher = document.querySelector('.gf-chatbot__launcher');
      if (launcher) launcher.click();
    });
  });

})();
		<?php return ob_get_clean();
	}
}
